### ISSUE TITLE
5.0 Lock Support

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#267]
<p>I'd like for GlazedLists to be able to use Java 5's locks rather than the Doug Lea implementation we're <br/>
using right now to pick up on their extra speed. Obviously the funky part is to make sure it can compile <br/>
and run under 1.4 and 5.0. So, here's my proposal:</p>

<p>One class could be compiled under 5.0 and checked in as its ".class" form. When the jar is built, the <br/>
class would be included. (The source would obviously be checked in somewhere, just not in the main <br/>
source tree... or excluded from the ant build script.)</p>

<p>If we decide that we don't want to include the 5.0 class, we could still do the LockFactory class and <br/>
allow the user to specify their own implementation via a System property. Here's a LockFactory <br/>
implementation that would do this:</p>

<p>------------------------<br/>
/**</p>
<ul>
	<li>Factory allows creation of the best locks for the VM we're running in.<br/>
 */<br/>
public class LockFactory {<br/>
	private static LockFactory instance;</li>
</ul>

<p>	static {<br/>
		LockFactory jse5_lock_factory = null;</p>

<p>		// See if the user has specified their own lock factory implementation<br/>
		try {<br/>
			String user_lock_factory = System.getProperty("glazedlists.lockfactory", null);<br/>
			if (user_lock_factory != null) {<br/>
				try </p>
{
					jse5_lock_factory = (LockFactory) Class.forName(
						user_lock_factory).newInstance();
				}
<p>				catch (Exception ex) </p>
{
					System.err.println("Unable to load user-defined lock factory. " +
						"Default will be used.");
					ex.printStackTrace();
				}
<p>				catch (NoClassDefFoundError er) </p>
{
					System.err.println("Unable to load user-defined lock factory. " +
						"Default will be used.");
					er.printStackTrace();
				}
<p>			}<br/>
		}<br/>
		catch(SecurityException ex ) {}			// ignore</p>

<p>		try </p>
{
			// See if we can find the 5.0 lock class
			Class.forName("java.util.concurrent.locks.ReentrantReadWriteLock");

			// If so, see if we can load the 5.0 LockFactory class
			jse5_lock_factory = (LockFactory) Class.forName(
				"ca.odell.glazedlists.util.concurrent.JSE5LockFactory").newInstance();
		}
<p>		catch (Exception ex) {}					// ignore<br/>
		catch (NoClassDefFoundError er) {}		// ignore</p>

<p>		// See if we should print a debugging message saying what locks we're using<br/>
		boolean debug = false;<br/>
		try </p>
{
			debug = System.getProperty("glazedlists.lockfactory.debug",null) != null;
		}
<p> catch( SecurityException ex ) {}		// ignore</p>

<p>		// Set the singleton instance<br/>
		if (jse5_lock_factory != null) </p>
{
			if (debug) System.out.println("*** GlazedLists will use 5.0+ Locking ***");
			instance = jse5_lock_factory;
		}
<p> else </p>
{
			if (debug) System.out.println("*** GlazedLists will use 1.2+ Locking ***");
			instance = new LockFactory();
		}
<p>	}</p>

<p>	/**</p>
<ul>
	<li>Create a new 
{@link ReadWriteLock}
<p>.<br/>
	 */<br/>
	public static ReadWriteLock createReadWriteLock() </p>
{
		return instance._internalCreateReadWriteLock();
	}</li>
</ul>

<p>	/**</p>
<ul>
	<li>Create a new 
{@link Lock}
<p>.<br/>
	 */<br/>
	public static Lock createLock() </p>
{
		return instance._internalCreateLock();
	}</li>
</ul>

<p>	/**</p>
<ul>
	<li>Should be overridden by LockFactory implementations to return a ReadWriteLock</li>
	<li>implementation. The default implementation returns a 
{@link J2SE12ReadWriteLock},<br/>
	 * which works in 1.2+ VM's.<br/>
	 */<br/>
	protected ReadWriteLock _internalCreateReadWriteLock() {
		return new J2SE12ReadWriteLock();
	}<br/>
<br/>
<br/>
	/**<br/>
	 * Should be overridden by LockFactory implementations to return a Lock implementation.<br/>
	 * The default implementation uses a {@link J2SE12ReadWriteLock}
<p>, which works in 1.2+</p></li>
	<li>VM's.<br/>
	 */<br/>
	protected Lock _internalCreateLock() 
{
		return new J2SE12ReadWriteLock().writeLock();
	}
<p>}<br/>
------------------------</p></li>
</ul>

<p>Implementing 5.0 support is them pretty easy.</p>
<i>[GLAZEDLISTS-251] created by reden</i>
